name: Publish to npm

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Installing rollup
        run: npm install -g rollup
      - name: Prepare environment & build
        run: |
          npm ci
          npm pkg fix
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run unit tests
        continue-on-error: true
        run: |
          npm run test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
